### PR TITLE
fix can't find some English listen mp3 that songs time less than 10 s…

### PR DESCRIPTION
**Pull request by mkzpd**
fix can't find some English listen mp3 that songs time less than 10 seconds long.

### CODE REVIEW

**Comment by mkzpd** [comment]
modify albums interface layout

**Comment by ShokhrukhbekYuldoshev** [comment]
Thanks for submitting a PR. Unfortunately I can't merge it because, sorting this way is not proper imho. In the future releases I will add an option to fetch audios which are less than 10 seconds. BTW, I fixed album and artist pages. Please chech the newest version out.

PS: EDITED

**Comment by mkzpd** [comment]
I see you fix album and artist pages in version 1.2.0, I think newer is better than older, it's very good.

By the way, you said _In the future releases I will add an option to fetch audios which are more than 10 seconds._ , I think it should be _In the future releases I will add an option to fetch audios which are **less** than 10 seconds._  (In simple terms more --> less).

**Comment by ShokhrukhbekYuldoshev** [comment]
> I see you fix album and artist pages in version 1.2.0, I think newer is better than older, it's very good.
> 
> By the way, you said _In the future releases I will add an option to fetch audios which are more than 10 seconds._ , I think it should be _In the future releases I will add an option to fetch audios which are **less** than 10 seconds._ (In simple terms more --> less).

Added an option to see songs less than 10 seconds.

**Comment by ShokhrukhbekYuldoshev** [comment]
> fix can't find some English listen mp3 that songs time less than 10 seconds long.

Added an option to see songs less than 10 seconds.

**Pull request closed without merging**
